### ISSUE TITLE
show to configure SPARKMONITOR_KERNEL_PORT

### ISSUE THREAD

**Issue by wangqiaoshi** [krishnan-r/sparkmonitor#5]
how to configure SPARKMONITOR_KERNEL_PORT

> SPARKLISTENER: Exception creating socket:java.lang.NumberFormatException: For input string: "ERRORNOTFOUND"

**Comment by krishnan-r** [comment]
`SPARKMONITOR_KERNEL_PORT` is an environment variable set by the IPython kernel extension [here](https://github.com/krishnan-r/sparkmonitor/blob/master/extension/sparkmonitor/kernelextension.py#L196), which is used by the scala listener that collects data [here](https://github.com/krishnan-r/sparkmonitor/blob/master/extension/scalalistener/CustomListener.scala#L34). The scala code sends data through a socket to the kernel using this port.

The error maybe because the [kernel extension](https://github.com/krishnan-r/sparkmonitor/blob/master/extension/sparkmonitor/kernelextension.py) has an error or has not started, so the environement variable is unset.

The kernel extension writes logs to a file in the same folder as the notebook, see if this file is created, and check if the kernel extension is loaded.

Instructions to configure each component, can be found [here](https://krishnan-r.github.io/sparkmonitor/install.html).

**Comment by wangqiaoshi** [comment]
kernel extension Has not started.
