### ISSUE TITLE
UI not visible in notebook

### ISSUE THREAD

**Issue by cristina-grosu** [krishnan-r/sparkmonitor#7]
I'm running spark and jupyter notebook in a docker container and I configured the sparkmonitor extension is loaded in the config files. I am running a Spark job in the notebook using the example provided in the github repo. However, even though the job is completed and i can see the final results and the stages in the logs, the UI does not display the screen shots described. What could happen?

**Comment by krishnan-r** [comment]
Firstly thank you for your interest in the project.

Here are some possible issues that could be the reason

- Jupyter needs to be at least 5.x. Some APIs of Jupyter don't work right in 4.x.x.
- You have to use the configuration object provided by the extension.
- The configuration/installation may not be right. 
There are three components that work together. A frontend javascript nbextension, a jupyter webserver extension, and an ipython kernel extension. 

Check the browser console for any errors and if the frontend javascript extension has started. 

The IPython kernel extension has to be configured in the config files. Since you are running in a container your environment could be different. A log file is created by the kernel extension in the same folder as the notebook.

Check the jupyter console for any errors.

Since you are using docker, you may try this [docker container](https://hub.docker.com/r/krishnanr/sparkmonitor/),( which was working the last time I checked) if you want to see what it does.

**Comment by cristina-grosu** [comment]
I tested the docker container and it looks that it is not working.

**Comment by krishnan-r** [comment]
Yes there seems to be a problem. It is not working. I shall look into it.

**Comment by cristina-grosu** [comment]
I get a similar error to #6 indeed. I tried to solve it by installing ipywidget, without any positive result. Keep us up to date.

**Comment by krishnan-r** [comment]
I think I have identified the issue. Please see #6 and lets continue the discussion there. Closing this for now.
